services:

  postgres:
    image: postgres:17
    container_name: royal64-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: royal64
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Royal64@2026

    ports:
      - "5432:5432"

    volumes:
      - royal64_pgdata:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d royal64"]
      interval: 5s
      timeout: 5s
      retries: 20

  redis:
    image: redis:8-alpine
    container_name: royal64-redis
    restart: unless-stopped

    ports:
      - "6379:6379"

    command: redis-server --appendonly yes

    volumes:
      - royal64_redis:/data

volumes:
  royal64_pgdata:
  royal64_redis: