"""create matches games moves

Revision ID: df4050485133
Revises: f9cd9572de3c
Create Date: 2026-07-21 03:10:35.349988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df4050485133'
down_revision: Union[str, Sequence[str], None] = 'f9cd9572de3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('offer_id', sa.UUID(), nullable=False),
    sa.Column('white_player_id', sa.UUID(), nullable=False),
    sa.Column('black_player_id', sa.UUID(), nullable=False),
    sa.Column('winner_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('games_required', sa.Integer(), nullable=False),
    sa.Column('white_score', sa.Integer(), nullable=False),
    sa.Column('black_score', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('WAITING', 'ACTIVE', 'FINISHED', 'CANCELLED', name='matchstatus'), nullable=False),
    sa.Column('escrow_contract', sa.String(length=128), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['black_player_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['offer_id'], ['match_offers.id'], ),
    sa.ForeignKeyConstraint(['white_player_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('games',
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('game_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('WAITING', 'PLAYING', 'FINISHED', name='gamestatus'), nullable=False),
    sa.Column('result', sa.Enum('WHITE', 'BLACK', 'DRAW', name='gameresult'), nullable=True),
    sa.Column('time_control_minutes', sa.Integer(), nullable=False),
    sa.Column('white_time_ms', sa.Integer(), nullable=False),
    sa.Column('black_time_ms', sa.Integer(), nullable=False),
    sa.Column('active_white', sa.Boolean(), nullable=False),
    sa.Column('disconnect_white', sa.Integer(), nullable=False),
    sa.Column('disconnect_black', sa.Integer(), nullable=False),
    sa.Column('fen', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('moves',
    sa.Column('game_id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('move_number', sa.Integer(), nullable=False),
    sa.Column('san', sa.String(length=32), nullable=False),
    sa.Column('uci', sa.String(length=8), nullable=False),
    sa.Column('fen_after', sa.String(length=128), nullable=False),
    sa.Column('move_time_ms', sa.Integer(), nullable=False),
    sa.Column('is_check', sa.Boolean(), nullable=False),
    sa.Column('is_checkmate', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('moves')
    op.drop_table('games')
    op.drop_table('matches')
    # ### end Alembic commands ###
